### ISSUE TITLE
Challenge error: could not get operation status

### ISSUE THREAD

**Issue by asbachb** [ZencashOfficial/nodetracker#51]
```
Challenge error: could not get operation status.
 { Error: socket hang up
     at createHangUpError (_http_client.js:330:15)
     at Socket.socketOnEnd (_http_client.js:423:23)
     at Socket.emit (events.js:165:20)
     at endReadableNT (_stream_readable.js:1101:12)
     at process._tickCallback (internal/process/next_tick.js:152:19) code: 'ECONNRESET' }
```

**Comment by ADumaine** [comment]
This is an problem between the tracker app and zend.  The tracker communicates with zend just like zen-cli does.  The connection was reset (ECONNRESET) and should fix itself.  

This can be tested for errors by trying a 'zen-cli getinfo'.

If it node has not run another challenge, send one using the 'Send Challenge' email on the node details page.

**Comment by asbachb** [comment]
This happend multiple times when executing challenges and afterwards the tracker is in some strange state. Maybe it's a good idea to send kind a reset event to tracker server for resetting running challenges for example.

**Comment by ADumaine** [comment]
If this keeps happening you can try the following:
stop zend with: zen-cli stop
wait 10 seconds
start zend with: zend --rescan

**Comment by ADumaine** [comment]
Closed due to no activity.
