### ISSUE TITLE
SyntaxError: Unexpected token W in JSON at position 0

### ISSUE THREAD

**Issue by cybercrypto** [ZencashOfficial/nodetracker#52]
Hi,
I'm getting the following error when trying to submit challenge.
.....
2018-03-06 10:33:50 GMT -- Elapsed challenge time=110  status=executing
2018-03-06 10:33:50 GMT -- Elapsed challenge time=110  status=executing
2018-03-06 10:33:50 GMT -- Elapsed challenge time=110  status=executing
2018-03-06 10:33:50 GMT -- Elapsed challenge time=110  status=executing
2018-03-06 10:33:50 GMT -- Elapsed challenge time=110  status=executing                     
2018-03-06 10:34:00 GMT -- Elapsed challenge time=120  status=executing                     
2018-03-06 10:35:26 GMT -- Challenge error: could not get operation status.                 
SyntaxError: Unexpected token W in JSON at position 0                                       
    at JSON.parse (<anonymous>)                                                             
    at IncomingMessage.res.on (/home/node/secnodetracker/node_modules/zcash/index.js:75:23) 
    at emitNone (events.js:111:20)                                                          
    at IncomingMessage.emit (events.js:208:7)                                               
    at endReadableNT (_stream_readable.js:1055:12)                                          
    at _combinedTickCallback (internal/process/next_tick.js:138:11)                         
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by psyraxaus** [comment]
This suggests that your Zend daemon is crashing.

How much memory do you have?

Please run: free -h

**Comment by cybercrypto** [comment]
Memory was at 50% of 8GB memory. Balance was at 0.19844.
It happened during system startup/boot.

**Comment by cybercrypto** [comment]
Like i said it was at 50% and now is at 60%.
              total        used        free      shared  buff/cache   available
Mem:           7973        4643         171          66        3158        2984
Swap:          6831        2508        4323

And also the secnodetracker didnt crash.
2018-03-06 10:33:50 GMT -- Elapsed challenge time=110  status=executing                                                                                           
2018-03-06 10:34:00 GMT -- Elapsed challenge time=120  status=executing                                                                                           
2018-03-06 10:35:26 GMT -- Challenge error: could not get operation status.                                                                                       
SyntaxError: Unexpected token W in JSON at position 0                                                                                                             
    at JSON.parse (<anonymous>)                                                                                                                                   
    at IncomingMessage.res.on (/home/node/secnodetracker/node_modules/zcash/index.js:75:23)                                                                       
    at emitNone (events.js:111:20)                                                                                                                                
    at IncomingMessage.emit (events.js:208:7)                                                                                                                     
    at endReadableNT (_stream_readable.js:1055:12)                                                                                                                
    at _combinedTickCallback (internal/process/next_tick.js:138:11)                                                                                               
    at process._tickCallback (internal/process/next_tick.js:180:9)                                                                                                
2018-03-06 10:35:31 GMT -- Stat check: connected to:ts1.sea blocks:268387 peers:8 bal:0.1986 isValidBal:true queueDepth:0 lastChalBlock:268335 lastExecSec:308.51 
2018-03-06 10:35:31 GMT -- Stats received by ts1.sea                                                                                                              
2018-03-06 10:41:11 GMT -- Stat check: connected to:ts1.sea blocks:268452 peers:8 bal:0.1984 isValidBal:true queueDepth:0 lastChalBlock:268335 lastExecSec:308.51 
2018-03-06 10:41:11 GMT -- Stats received by ts1.sea                                                                                                              
2018-03-06 10:47:10 GMT -- Stat check: connected to:ts1.sea blocks:268463 peers:8 bal:0.1984 isValidBal:true queueDepth:0 lastChalBlock:268335 lastExecSec:308.51 


snippet from debug.log
2018-03-06 10:33:11 UpdateTip: new best=0000000018c7484971fcfb99a49398bd611e9f77d5f7967b99d12da50a994030  height=268346  log2_work=48.890277  tx=1556410  date=2018-03-06 06:06:36 progress=0.999786  cache=1.8MiB(237tx)
2018-03-06 10:33:21 UpdateTip: new best=000000006cfee766c8793ccb384a3520c86d21afa85111b68ab07a4d2aaf5561  height=268347  log2_work=48.890302  tx=1556429  date=2018-03-06 06:07:24 progress=0.999787  cache=1.8MiB(239tx)
2018-03-06 10:33:31 UpdateTip: new best=000000003ebfa659ff9a5d8fc3c3e2ccf7a38ba448e8847813444bacdd9d0f6d  height=268348  log2_work=48.890324  tx=1556461  date=2018-03-06 06:14:49 progress=0.999792  cache=1.8MiB(243tx)
2018-03-06 10:33:34 UpdateTip: new best=00000000196973cc3ec2575f2d1e086e64ac09301eeddf20ad7e5c3c7ccb227b  height=268349  log2_work=48.890345  tx=1556463  date=2018-03-06 06:14:59 progress=0.999793  cache=1.8MiB(244tx)
2018-03-06 10:33:36 UpdateTip: new best=0000000009813a21485cf9de52da4b5b7767f7aeed1375bebf8e2d262849281e  height=268350  log2_work=48.890366  tx=1556470  date=2018-03-06 06:16:43 progress=0.999794  cache=1.8MiB(246tx)
2018-03-06 10:33:50 UpdateTip: new best=00000000119511b9f97a2706801a865b50ba0e77a8d62d91169dd9c7016b7248  height=268351  log2_work=48.890386  tx=1556518  date=2018-03-06 06:19:38 progress=0.999796  cache=2.3MiB(298tx)
2018-03-06 10:33:53 UpdateTip: new best=00000000857436ab8b4d5fa41287bada0db34d4a48d3b52bbb9d036ec753988c  height=268352  log2_work=48.890405  tx=1556527  date=2018-03-06 06:22:04 progress=0.999798  cache=2.3MiB(300tx)
2018-03-06 10:33:53 UpdateTip: new best=0000000046adef0c58dec2f1ce6d60b2841ba3b990e51591449aaabc6dd2330c  height=268353  log2_work=48.890423  tx=1556528  date=2018-03-06 06:22:21 progress=0.999798  cache=2.3MiB(301tx)
2018-03-06 10:33:53 UpdateTip: new best=0000000071ee6ebcefcffec82f7060db2fdfe31b588d4bc9a7d0e1e439a1f50b  height=268354  log2_work=48.890441  tx=1556529  date=2018-03-06 06:22:43 progress=0.999799  cache=2.3MiB(302tx)
2018-03-06 10:33:54 UpdateTip: new best=0000000047fd64ace0f1e3f75cc979bea2bf19d1bbb7975b3edc603f1c8b3dc2  height=268355  log2_work=48.890459  tx=1556532  date=2018-03-06 06:23:16 progress=0.999799  cache=2.6MiB(331tx)
2018-03-06 10:33:55 UpdateTip: new best=00000000570af2000a00b0ee039396233fb48f8a71888bd29609852951ac0faf  height=268356  log2_work=48.890476  tx=1556534  date=2018-03-06 06:23:28 progress=0.999799  cache=2.6MiB(332tx)
2018-03-06 10:33:55 UpdateTip: new best=00000000575c9f738f41f3816bf14df7fe815f0b2294c6299dd4e611c5b94d51  height=268357  log2_work=48.890493  tx=1556535  date=2018-03-06 06:23:32 progress=0.999799  cache=2.6MiB(333tx)
2018-03-06 10:33:55 UpdateTip: new best=000000005a53cec50b6af84a81356a9563bf47920a85a205ea74d212a24583da  height=268358  log2_work=48.89051  tx=1556536  date=2018-03-06 06:23:49 progress=0.999799  cache=2.6MiB(334tx)
2018-03-06 10:33:55 UpdateTip: new best=00000000636a479357aa0b0ac1eec51641c236e0873bf597a8a6bb7e57b585cb  height=268359  log2_work=48.890525  tx=1556538  date=2018-03-06 06:24:16 progress=0.999800  cache=2.6MiB(337tx)
2018-03-06 10:33:55 UpdateTip: new best=000000000d97b601c87e10e29f4c8a1441003440ddd1773185ad09d78d1203e6  height=268360  log2_work=48.890541  tx=1556539  date=2018-03-06 06:24:21 progress=0.999800  cache=2.6MiB(338tx)
2018-03-06 10:33:56 UpdateTip: new best=000000000f08b8ff93f30374c22fda2529639cae0b208099df7a5197fde22d34  height=268361  log2_work=48.890555  tx=1556541  date=2018-03-06 06:24:47 progress=0.999800  cache=2.6MiB(340tx)
2018-03-06 10:33:56 UpdateTip: new best=00000000ca65988fbaf7dd9bf8c37554d3617347edf52c4b38244b65e049f77a  height=268362  log2_work=48.89057  tx=1556542  date=2018-03-06 06:24:57 progress=0.999800  cache=2.6MiB(341tx)
2018-03-06 10:33:56 UpdateTip: new best=0000000076596eaf6e9eaf4dce0c8bb49d92acf254f20f5da4aff749cdb14358  height=268363  log2_work=48.890585  tx=1556545  date=2018-03-06 06:25:04 progress=0.999800  cache=3.2MiB(407tx)
2018-03-06 10:33:56 UpdateTip: new best=00000000a3fb507921e47454f76f42d2d6248a9f79a32228588e2ef501bfa184  height=268364  log2_work=48.8906  tx=1556546  date=2018-03-06 06:25:15 progress=0.999801  cache=3.2MiB(408tx)
2018-03-06 10:33:57 UpdateTip: new best=000000001c855e427e4e5e33d9a80e4c3bfea7fe9f47f34f10a5673be6074139  height=268365  log2_work=48.890616  tx=1556547  date=2018-03-06 06:25:19 progress=0.999801  cache=3.2MiB(409tx)
2018-03-06 10:33:57 UpdateTip: new best=000000002efdf9f60ad6f8d7eef804a22249a50f4254860b916c690a0b1f0e29  height=268366  log2_work=48.890633  tx=1556548  date=2018-03-06 06:25:40 progress=0.999801  cache=3.2MiB(410tx)
2018-03-06 10:33:57 UpdateTip: new best=000000005e700dfd55f336df709ea6246ca04a1c457b6a19e41ef455a308c33b  height=268367  log2_work=48.890649  tx=1556549  date=2018-03-06 06:25:46 progress=0.999801  cache=3.2MiB(411tx)
2018-03-06 10:33:57 UpdateTip: new best=000000009fa3a50163fd7ea2b175bfc05e0db7a31f887559f8d1f82885a2570c  height=268368  log2_work=48.890667  tx=1556551  date=2018-03-06 06:26:07 progress=0.999801  cache=3.2MiB(412tx)
2018-03-06 10:33:58 UpdateTip: new best=000000003bdea1c5b1be1fe0d4bb1c53e08ec2af03e643ab7521674bd5483484  height=268369  log2_work=48.890686  tx=1556554  date=2018-03-06 06:26:54 progress=0.999802  cache=3.2MiB(414tx)
2018-03-06 10:33:58 UpdateTip: new best=0000000022d1a0aec5e80e42e1c756c5489d5ba80a2e3dbb9c167d02608a7d93  height=268370  log2_work=48.890705  tx=1556556  date=2018-03-06 06:27:29 progress=0.999802  cache=3.2MiB(416tx)
2018-03-06 10:33:59 UpdateTip: new best=0000000025ff6717430b630e0aa5b992109c1bfa0e3c47e45e6f319fabbac6fd  height=268371  log2_work=48.890724  tx=1556562  date=2018-03-06 06:30:04 progress=0.999804  cache=3.2MiB(421tx)

**Comment by psyraxaus** [comment]
Thank you, could you please have a look around 2018-03-06 10:34:00 GMT and 2018-03-06 10:35:26 GMT in the debug.log for any large spaces or any thing. 

I just noticed you are connected to the SEA region.  Could you please try changing to either na or eu, restart your tracker, and then send a challenge to the node

**Comment by cybercrypto** [comment]
Obviously there is a bug in secnodetracker code somewhere.

A zend --rescan combined with a manual challenge request through email works for now.
I'm waiting for the next cycle of auto challenge request to see if secnodetracker errors again.

**Comment by psyraxaus** [comment]
Usually the error that you are experiencing indicates that there is an issue with the tracker connecting to the zend daemon and getting the json response via http, and from past experience a crashed zend daemon is the cause.  That was the reason why I was asking if there were any gaps in the debug.log around the time of the error

**Comment by cybercrypto** [comment]
Bad news. Automated challenge request succeed but the tracking site said otherwise. I don't know the hell is going on.

https://securenodes.sea.zensystem.io/nodes/28653/chals 
2818673 | 2018-03-07 12:06:23 | 2018-03-07 12:09:26 | 03:03 | 181 | fail | exceeded reply time or timed out
-- | -- | -- | -- | -- | -- | --

secnodetracker log
============
Using zcEhn6knpagkgrvgZcz9Hmgi6S3vzmkQSNqRJQ2BXxbUKt95SV47afH8mpmctsMvt5Ym2qUvvP6nPzdB3bpApdkLUFvVrfY for challenge. bal=0.1982
OperationId=opid-61a884f1-9e8a-493c-ae57-5456a6ed64a2
2018-03-07 12:06:33 GMT -- Elapsed challenge time=10  status=executing
2018-03-07 12:06:43 GMT -- Elapsed challenge time=20  status=executing
2018-03-07 12:06:53 GMT -- Elapsed challenge time=30  status=executing
2018-03-07 12:07:03 GMT -- Elapsed challenge time=40  status=executing
2018-03-07 12:07:13 GMT -- Elapsed challenge time=50  status=executing
2018-03-07 12:07:23 GMT -- Elapsed challenge time=60  status=executing
2018-03-07 12:07:25 GMT -- Stat check: connected to:ts1.sea blocks:269048 peers:8 bal:0.1982 isValidBal:true queueDepth:0 lastChalBlock:268492 lastExecSec:199.17
2018-03-07 12:07:25 GMT -- Stats received by ts1.sea
2018-03-07 12:07:33 GMT -- Elapsed challenge time=70  status=executing
2018-03-07 12:07:44 GMT -- Elapsed challenge time=80  status=executing
2018-03-07 12:07:53 GMT -- Elapsed challenge time=90  status=executing
2018-03-07 12:08:04 GMT -- Elapsed challenge time=100  status=executing
2018-03-07 12:08:14 GMT -- Elapsed challenge time=110  status=executing
2018-03-07 12:08:24 GMT -- Elapsed challenge time=120  status=executing
2018-03-07 12:08:34 GMT -- Elapsed challenge time=130  status=executing
2018-03-07 12:08:44 GMT -- Elapsed challenge time=140  status=executing
2018-03-07 12:08:54 GMT -- Elapsed challenge time=150  status=executing
2018-03-07 12:09:04 GMT -- Elapsed challenge time=160  status=executing
2018-03-07 12:09:14 GMT -- Elapsed challenge time=170  status=executing
2018-03-07 12:09:24 GMT -- Elapsed challenge time=180  status=executing
2018-03-07 12:09:26 GMT -- Challenge submit: success
2018-03-07 12:09:26 GMT -- Challenge result:success seconds:181.021148003
2018-03-07 12:09:26 GMT -- Challenge response received by ts1.sea
2018-03-07 12:09:28 GMT -- Clearing timer

log from zend
=========
2018-03-07 12:06:23 keypool reserve 2                                                                                                                                       
2018-03-07 12:06:23 keypool return 2                                                                                                                                        
2018-03-07 12:06:36 ERROR: AcceptToMemoryPool: joinsplit requirements not met                                                                                               
2018-03-07 12:06:40 ERROR: AcceptToMemoryPool: joinsplit requirements not met                                                                                               
2018-03-07 12:06:49 ERROR: AcceptToMemoryPool: joinsplit requirements not met                                                                                               
2018-03-07 12:06:55 ERROR: AcceptToMemoryPool: joinsplit requirements not met                                                                                               
2018-03-07 12:06:58 ERROR: AcceptToMemoryPool: joinsplit requirements not met                                                                                               
2018-03-07 12:07:04 ERROR: AcceptToMemoryPool: joinsplit requirements not met                                                                                               
2018-03-07 12:07:10 ERROR: AcceptToMemoryPool: joinsplit requirements not met                                                                                               
2018-03-07 12:07:25 keypool reserve 2                                                                                                                                       
2018-03-07 12:07:25 keypool return 2                                                                                                                                        
2018-03-07 12:07:25 keypool reserve 2                                                                                                                                       
2018-03-07 12:07:25 keypool return 2                                                                                                                                        
2018-03-07 12:07:37 ERROR: AcceptToMemoryPool: joinsplit requirements not met                                                                                               
2018-03-07 12:07:44 ERROR: AcceptToMemoryPool: joinsplit requirements not met                                                                                               
2018-03-07 12:07:48 ERROR: AcceptToMemoryPool: joinsplit requirements not met                                                                                               
2018-03-07 12:07:57 ERROR: AcceptToMemoryPool: joinsplit requirements not met                                                                                               
2018-03-07 12:08:31 ERROR: AcceptToMemoryPool: joinsplit requirements not met                                                                                               
2018-03-07 12:08:31 ERROR: AcceptToMemoryPool: joinsplit requirements not met                                                                                               
2018-03-07 12:08:57 ERROR: AcceptToMemoryPool: joinsplit requirements not met                                                                                               
2018-03-07 12:09:17 ERROR: AcceptToMemoryPool: joinsplit requirements not met                                                                                               
2018-03-07 12:09:22 ERROR: AcceptToMemoryPool: joinsplit requirements not met                                                                                               
2018-03-07 12:09:24 AddToWallet 176fe3d26d636b7ed604dd3aefd3e7c58f71629254969828e75c5cd43f0bd231  new                                                                       
2018-03-07 12:09:24 opid-61a884f1-9e8a-493c-ae57-5456a6ed64a2: z_sendmany finished (status=success, txid=176fe3d26d636b7ed604dd3aefd3e7c58f71629254969828e75c5cd43f0bd231)  
2018-03-07 12:09:26 keypool reserve 2                                                                                                                                       
2018-03-07 12:09:26 keypool return 2                                                                                                                                        

Why am I failing when it was under 300 seconds?

**Comment by ADumaine** [comment]
The 'AcceptToMemoryPool: joinsplit requirements not met' may be zen not being fully sync'd or it may need to be reindexed.   You can try restarting with:  zend -reindex.

**Comment by blbradley** [comment]
FWIW, I also encountered this error. It _was_ due to zend not having enough memory for the transaction.

```2018-03-28 16:48:21 opid-818556d0-d1b9-449b-99e2-b5331b105e7f: z_sendmany finished (status=failed, error=general exception: std::bad_alloc)```

**Comment by PeaStew** [comment]
@ADumaine these errors "ERROR: AcceptToMemoryPool: joinsplit requirements not met" are "normal" it is not related to the node, these are other people's transactions trying to do double spends usually.
@blbradley bad_alloc is the zend process running out of memory (RAM + Swap)

**Comment by rmeleromira** [comment]
Just got this error as well, and my challenge failed although the z_sendmany transaction was successful.

```
2018-04-29 17:55:28 opid-0b075b46-e822-450d-bd2e-e9e7be3ba3e3: z_sendmany finished (status=success, txid=836efbda1032bf279300d82c71ad9f757bfb976b95ca1d12fa918430c8e45647)
```

```
Apr 29 12:52:51 sn2.cryptomn.trade node[4780]: OperationId=opid-0b075b46-e822-450d-bd2e-e9e7be3ba3e3
Apr 29 12:53:01 sn2.cryptomn.trade node[4780]: 2018-04-29 17:53:01 GMT -- Elapsed challenge time=10  status=executing
Apr 29 12:53:11 sn2.cryptomn.trade node[4780]: 2018-04-29 17:53:11 GMT -- Elapsed challenge time=20  status=executing
Apr 29 12:53:22 sn2.cryptomn.trade node[4780]: 2018-04-29 17:53:22 GMT -- Elapsed challenge time=30  status=executing
Apr 29 12:53:22 sn2.cryptomn.trade node[4780]: 2018-04-29 17:53:22 GMT -- Elapsed challenge time=30  status=executing
Apr 29 12:53:41 sn2.cryptomn.trade node[4780]: 2018-04-29 17:53:41 GMT -- Elapsed challenge time=50  status=executing
Apr 29 12:53:51 sn2.cryptomn.trade node[4780]: 2018-04-29 17:53:51 GMT -- Elapsed challenge time=60  status=executing
Apr 29 12:53:51 sn2.cryptomn.trade node[4780]: 2018-04-29 17:53:51 GMT -- Elapsed challenge time=60  status=executing
Apr 29 12:54:01 sn2.cryptomn.trade node[4780]: 2018-04-29 17:54:01 GMT -- Elapsed challenge time=70  status=executing
Apr 29 12:54:11 sn2.cryptomn.trade node[4780]: 2018-04-29 17:54:11 GMT -- Elapsed challenge time=80  status=executing
Apr 29 12:55:16 sn2.cryptomn.trade node[4780]: 2018-04-29 17:55:16 GMT -- Challenge error: could not get operation status.
Apr 29 12:55:16 sn2.cryptomn.trade node[4780]: SyntaxError: Unexpected token W in JSON at position 0
Apr 29 12:55:16 sn2.cryptomn.trade node[4780]:     at JSON.parse (<anonymous>)
Apr 29 12:55:16 sn2.cryptomn.trade node[4780]:     at IncomingMessage.res.on (/home/zend/secnodetracker/node_modules/zcash/index.js:75:23)
Apr 29 12:55:16 sn2.cryptomn.trade node[4780]:     at IncomingMessage.emit (events.js:185:15)
Apr 29 12:55:16 sn2.cryptomn.trade node[4780]:     at endReadableNT (_stream_readable.js:1106:12)
Apr 29 12:55:16 sn2.cryptomn.trade node[4780]:     at process._tickCallback (internal/process/next_tick.js:178:19)
```

https://securenodes2.eu.zensystem.io/nodes/45226/chals

Challenge id 5893843

**Comment by psyraxaus** [comment]
Do you have maxconnections= set in your zen.conf?

**Comment by ADumaine** [comment]
Version 0.3.1+ of the nodetracker have replaced the rpc module and handle 'Unexpected token W..' error differently.  There should now be clearer error messages to trouble shoot the issue.
